spring:
  build:
    version: 0.0.1
  application:
    name: challenge
    description: challenge test
  web:
    resources:
      add-mappings: false
  mvc:
    servlet:
      path: /challenge
    throw-exception-if-no-handler-found: true
logging:
  level:
    _org.springframework.web.servlet.HandlerMapping.Mappings: debug